//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface ChatPrx extends com.zeroc.Ice.ObjectPrx
{
    default void registerUser(String username, CallbackPrx callback)
    {
        registerUser(username, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void registerUser(String username, CallbackPrx callback, java.util.Map<String, String> context)
    {
        _iceI_registerUserAsync(username, callback, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> registerUserAsync(String username, CallbackPrx callback)
    {
        return _iceI_registerUserAsync(username, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> registerUserAsync(String username, CallbackPrx callback, java.util.Map<String, String> context)
    {
        return _iceI_registerUserAsync(username, callback, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param iceP_callback -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_registerUserAsync(String iceP_username, CallbackPrx iceP_callback, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "registerUser", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                     ostr.writeProxy(iceP_callback);
                 }, null);
        return f;
    }

    default void listClients(String username)
    {
        listClients(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void listClients(String username, java.util.Map<String, String> context)
    {
        _iceI_listClientsAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> listClientsAsync(String username)
    {
        return _iceI_listClientsAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> listClientsAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_listClientsAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_listClientsAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "listClients", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, null);
        return f;
    }

    default void sendMessage(String message, String fromUser, String destUser)
    {
        sendMessage(message, fromUser, destUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendMessage(String message, String fromUser, String destUser, java.util.Map<String, String> context)
    {
        _iceI_sendMessageAsync(message, fromUser, destUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendMessageAsync(String message, String fromUser, String destUser)
    {
        return _iceI_sendMessageAsync(message, fromUser, destUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendMessageAsync(String message, String fromUser, String destUser, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageAsync(message, fromUser, destUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_message -
     * @param iceP_fromUser -
     * @param iceP_destUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendMessageAsync(String iceP_message, String iceP_fromUser, String iceP_destUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_message);
                     ostr.writeString(iceP_fromUser);
                     ostr.writeString(iceP_destUser);
                 }, null);
        return f;
    }

    default void broadCastMessage(String message, String fromUser)
    {
        broadCastMessage(message, fromUser, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void broadCastMessage(String message, String fromUser, java.util.Map<String, String> context)
    {
        _iceI_broadCastMessageAsync(message, fromUser, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> broadCastMessageAsync(String message, String fromUser)
    {
        return _iceI_broadCastMessageAsync(message, fromUser, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> broadCastMessageAsync(String message, String fromUser, java.util.Map<String, String> context)
    {
        return _iceI_broadCastMessageAsync(message, fromUser, context, false);
    }

    /**
     * @hidden
     * @param iceP_message -
     * @param iceP_fromUser -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_broadCastMessageAsync(String iceP_message, String iceP_fromUser, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "broadCastMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_message);
                     ostr.writeString(iceP_fromUser);
                 }, null);
        return f;
    }

    default void printString(String s)
    {
        printString(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void printString(String s, java.util.Map<String, String> context)
    {
        _iceI_printStringAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> printStringAsync(String s)
    {
        return _iceI_printStringAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> printStringAsync(String s, java.util.Map<String, String> context)
    {
        return _iceI_printStringAsync(s, context, false);
    }

    /**
     * @hidden
     * @param iceP_s -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_printStringAsync(String iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "printString", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_s);
                 }, null);
        return f;
    }

    default void fact(long n, CallbackPrx callback)
    {
        fact(n, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void fact(long n, CallbackPrx callback, java.util.Map<String, String> context)
    {
        _iceI_factAsync(n, callback, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> factAsync(long n, CallbackPrx callback)
    {
        return _iceI_factAsync(n, callback, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> factAsync(long n, CallbackPrx callback, java.util.Map<String, String> context)
    {
        return _iceI_factAsync(n, callback, context, false);
    }

    /**
     * @hidden
     * @param iceP_n -
     * @param iceP_callback -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_factAsync(long iceP_n, CallbackPrx iceP_callback, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "fact", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeLong(iceP_n);
                     ostr.writeProxy(iceP_callback);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatPrx.class, _ChatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatPrx.class, _ChatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatPrx.class, _ChatPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatPrx.class, _ChatPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatPrx.class, _ChatPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatPrx.class, _ChatPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatPrx ice_adapterId(String newAdapterId)
    {
        return (ChatPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatPrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatPrx ice_connectionCached(boolean newCache)
    {
        return (ChatPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatPrx ice_secure(boolean b)
    {
        return (ChatPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatPrx ice_preferSecure(boolean b)
    {
        return (ChatPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatPrx ice_collocationOptimized(boolean b)
    {
        return (ChatPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatPrx ice_twoway()
    {
        return (ChatPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatPrx ice_oneway()
    {
        return (ChatPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatPrx ice_batchOneway()
    {
        return (ChatPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatPrx ice_datagram()
    {
        return (ChatPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatPrx ice_batchDatagram()
    {
        return (ChatPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatPrx ice_compress(boolean co)
    {
        return (ChatPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatPrx ice_timeout(int t)
    {
        return (ChatPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatPrx ice_connectionId(String connectionId)
    {
        return (ChatPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Demo::Chat";
    }
}
